apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 18.2.0
      helm:
        valueFiles:
          - $values/apps/postgres/values.yaml
    - repoURL: https://github.com/edlundin/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/edlundin/homelab
      targetRevision: HEAD
      path: apps/postgres
      directory:
        include: "{postgres-secrets-sealed.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
