---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-auth-secret
  namespace: traefik
spec:
  encryptedData:
    users: AgCNfOygT1iPOKHXdG91s1JJ6C64m3kjqP0X1WgjDbQSLPcRiiTRy4iNwnXCYIZakDytOMEBGKkmed4WURmO8uqx+6QZNt5CxjFucBIr56DXmhVhM3NfAEtCnHYtp6lFuNrGDdEDrih9IIdXXkD/osLx/pnt+BAwWzi30fizCyz1kKdcd03bPwP0nbYcJ1QK/SkPwjcm6nWL65K9qjoKrYyyw24CQywB0gLFWXQju78UvpVMdnFwv0sq9TzcntSY2xsEOCtsb2SbiCmSFI6cKrW4tN6urB0Ml1nrrx8RqDKgZbSZ8IpY3ZftiXgYrVB/j54OX7puKBA+SfvFPEmtNwzYcW8hh0wokBiceOqi80vv8VhJTTSKAPTGybQrzWrApOqKa4r9alT9PX/q8ySUwJp7lQ4s3x6zopV3IfGFKuy0Ajl7QzOIp51Jt4NOLMmVzDzyGBmetbJn2u3LhGhrnNwyaL6JTV7sRIaE9wM1wWB70d9FRbaiSLyUsrnGm2kS3Ge00Mob4FsmEzQJZ5iFEZoTPoJTyMSYLDT9gtJCT2ZTvHFNJoBA0KQDkPahyd1BNjqoMCvy5yNFjLiBKgVxm4fj9Zlule/cwNQP8XHmeUWTXOFWwqCGVSJ4b2IKR081clHDk+BzYvDfpK5MXK4Q3CGM9Um2Rmav7HADVuqwpfeG+X8YG7NDVeacFvQJ9UyjoTDbpEOSviNZOAcdoDhCdgWr4NYsqG6pR0NEEe7JKza75SAfaHoz4SVx8V7E05p6scX9C2uSSatI4x2NKpPiouny6o4=
  template:
    metadata:
      name: traefik-auth-secret
      namespace: traefik
    type: Opaque
