---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-auth-secret
  namespace: traefik
spec:
  encryptedData:
    users: AgBK4Gnvj/T538zui6mYBHwa3KKRr+bLb8xhEwpwV3+5V4RxHagswLrsC9fnSECGNXRm9NzB63S0tQgG+BNo034phqStHjj8RrD3rZ1aPi5KINpVaQCyeTyIJJZzPrT+TadcbeA8vFP6oHJWLvF2jg/0xdnSPWAizDi2VdGajFag5Vl4aaOg0cNfeNb8JV0KOcds9Iqle6ndnJav+1bDp5IymhSW3epPWp3s/m/eMMcyXmA00yYjmnr20oPXMRPOryliWOjCNdX9WWig0YL05CeuIIXZzsnIwKygSbDYOeAn/PlnvBh7FbVn1LKHRVTPuxtuv0HNsx4UiMNe9ns0FFOZLtEbmHrImh6eDo5PjJqLLhvgA/pzba379FDJv4On1gQoJKDkBpmTlYW56TuP5w6HtQgp6NB6oX8aTwF9lNCww6qNdjcMP4u/bEjXfZG8083fzIHQ0PJENM326qyAyJ36HrXMkYRd3z8mFpk0t7HEpuCU/PU528jQQ/hs/fKAJ928lYrRRlBoYn2ZbrIKkBC5qqopXqfM/Mtl4nmYY3VBEjffMv9zPw8sMrzHfakyX0K1MrcY20tBo1G3OJ2c9LFhv2SxwnY1pkwILIwKxjjajBXRbwXPUcoIjlsAdtwxLru8qUrNAFbQKCw5S25PFmJWR+x+twzG+wfUuOyIhGYcsW8ZnXvt18Xjhzgs9Zujhneru6YQpRQuaYTp+NteNuh93wVTCek8D9CJ523e+u0dl3gKbx8RCa5A62BtqlH9eDLnxSF5yER/+5UqVSxi6PJmq78=
  template:
    metadata:
      name: traefik-auth-secret
      namespace: traefik
    type: Opaque
