---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-auth-secret
  namespace: traefik
spec:
  encryptedData:
    users: AgCjUAL5vpvK7d13AcSK2l6at9zktflvFGK9a+edcEcsH7jh/t0EZ4dHySCDMPaNHTD7pC2o+qkqJFTB4C/wHaP9JKd6lO6E0leR2+fn+GcotZRUqwXiYJtsFUmJo/OTF2Pt6uyS7Uz2sqizWZa9876bJWtT/CX3WF+VpoH1W6N2rOl7EK7LUAwamNBx6A8VKRIcYIqUHByZZvkXrBfL0i2/g8RbTVLiYWKQIQcAC2Ldw/lpAIuNf0K9IRR5gy4Cr0Kb/atLOcabOLdCMzPtk1/8oKlrXhjlkvsvt+J7G/f4aBri9kzC0mRJFwl8an19B2x1QXDNuyimQEzVp1Dxt64ONLEurz8wMrlA+Ojzn82sbzeZHx7O2xz7kNgYErcC74oJpPx2HnXsHdwmMrKkmS6jb5ObwyxyJQYq2CCDfzjLGQIs/9EqPB6H4gj3Mf7zI67nW1depcj10yBYa4/nUGUqIpYKEbp2jTKlZ+fIxbvydV03NGlhuaY9WKhfa2NIjYfOFxSRdl/rOB2nOlwCKfGzJFpqKfLS0DG9xNy1yj1O5EowFJ+Rrzz909UtHmq2Alp5OeaSFJ0bn6nCCgCharhmGCTdcsWfjRoUT6E7idCyCAfD0mIY5lUfk0DnL0reSokgAiXCVqpPNiDl4xMGB97dLs7ms2YfRCV0zeXZrOOslDErCiWU6Wfcp9+PLocGc39isb3MKveNGCFJHfhBNL9HzSDigdOZiPa0FEZgkw8JzzO3UspIXK6W3Uh3SVv7K9ZKZCczDl3NosDEenjzzMdksoo=
  template:
    metadata:
      name: traefik-auth-secret
      namespace: traefik
    type: Opaque
